export const POST_USER_REQUEST = "GET_USER_REQUEST";
export const POST_USER_SUCCESS = "GET_USER_SUCCESS";
export const POST_USER_FAIL = "GET_USER_FAIL";

export const GET_ALLUSER_REQUEST = "GET_ALLUSER_REQUEST";
export const GET_ALLUSER_SUCCESS = "GET_ALLUSER_SUCCESS";
export const GET_ALLUSER_FAIL = "GET_ALLUSER_FAIL";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
